export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'Apache Dolphin Scheduler(Incubating) Meetup 2019.10 Shanghai',
        author: 'William',
        dateStr: '2019-9-27',
        desc: 'Apache Dolphin Scheduler(Incubating) will organize a meetup in Shanghai  2019.10.26. Welcome to register.',
        link: '/en-us/blog/meetup_2019_10_26.html',
      },
      {
        title: 'FAQ of Apache DolphinScheduler',
        author: 'LidongDai',
        dateStr: '2021-03-20',
        desc: 'Apache Dolphin Scheduler(Incubating) will organize a meetup in Shanghai  2019.10.26. Welcome to register.',
        link: '/en-us/blog/FAQ.html',
      },          
       {
        title: 'Big Data Workflow Task Scheduling - Directed Acyclic Graph (DAG) for Topological Sorting',
        author: 'LidongDai',
        translator: 'QuakeWang',
        dateStr: '2021-05-06',
        desc: 'DAG: Full name Directed Acyclic Graph，referred to as DAG。Tasks in the workflow are assembled in the form of directed acyclic graphs, which are topologically traversed from nodes with zero indegrees of ingress until there are no successor nodes.',
        link: '/en-us/blog/DAG.html',
      },
         {
        title: 'Why did we split the big json that holds the tasks and relationships in the DolphinScheduler workflow definition?',
        author: 'JinyLeeChina',
        translator: 'QuakeWang',
        dateStr: '2021-06-03',
        desc: 'The task and relationship in the workflow of Dolphinscheduler is saved as the process_definition_json field that saves the process_definiton table in the database in a large JSON. If a workflow is large, this JSON field has become a result. Very big, you need to analyze JSON when using it, it costs very much, and the task cannot be reused, so the community plan launches the JSON split project.',
        link: '/en-us/blog/Json_Split.html',
      },
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: 'DolphinScheduler json详解',
        author: '进勇',
        editor: '小P',
        dateStr: '2021-05-29',
        desc: 'DolphinScheduler json拆解详细说明',
        link: '/zh-cn/blog/dolphinscheduler_json.html',
      },  
      {
        title: '为什么要把 DolphinScheduler 工作流定义中保存任务及关系的大 json 给拆了?',
        author: '进勇',
        editor: '王福政',
        dateStr: '2021-05-25',
        desc: '当前 DolphinScheduler 的工作流中的任务及关系保存时是以大 json 的方式保存到数据库中 process_definiton 表的 process_definition_json 字段，如果某个工作流很大比如有 1000 个任务，这个 json 字段也就随之变得非常大，在使用时需要解析 json，非常耗费性能，且任务没法重用，故社区计划启动 json 拆分项目。',
        link: '/zh-cn/blog/json_split.htmldolphinscheduler_json.html',
      },
      {
        title: '大数据工作流任务调度--有向无环图(DAG)之拓扑排序',
        author: '代立冬',
        translator: '王福政',
        dateStr: '2021-05-19',
        desc: 'DAG：全称是Directed Acyclic Graph，简称DAG。工作流中的任务以有向无环图的形式组合，从拓扑上看，这些节点的入口度为零，直到没有后续节点为止。',
        link: '/zh-cn/blog/DAG.html',
      },
      {
        title: 'Apache Dolphinscheduler 1.3.x 系列配置文件指南',
        author: '张伯毅',
        dateStr: '2021-01-05',
        target: '_blank',
        desc: '本文档为dolphinscheduler配置文件指南,针对版本为 dolphinscheduler-1.3.x 版本',
        link: 'https://mp.weixin.qq.com/s/gJUsGBHuMxw79VGH2ziZtg',
      },
      {
        title: 'DolphinScheduler & K8s 在优路科技的实践！',
        author: '李文禾',
        dateStr: '2020-11-12',
        target: '_blank',
        desc: '本文通过介绍DolphinScheduler on Kubernetes 在优路科技的实践，阐述了DolphinScheduler如何在云原生时代，更好地助力企业实现高效的数据调度解决方案',
        link: 'https://mp.weixin.qq.com/s/roNuuZ1AWySam5WwNQHwhg',
      },
      {
        title: 'Apache DolphinScheduler 需要的sudo，还可以这么玩，长见识了！',
        author: '海豚调度',
        dateStr: '2020-12-16',
        target: '_blank',
        desc: '这里推荐一下社区贡献者 import 的实践文章，写的非常赞，sudo 也是非常的痛点，也寻求一种更好的实现方式来实现多租户',
        link: 'https://mp.weixin.qq.com/s/5rRWMoT0DLMcOdDl-mrsRQ',
      },
      {
        title: 'Apache Dolphin Scheduler(Incubating)将于2019.10在上海举行见面会',
        author: '郭炜',
        dateStr: '2019-9-27',
        desc: 'Apache Dolphin Scheduler(Incubating) 将于2019年10月26日在上海组织一次会议，欢迎踊跃报名。 ',
        link: '/zh-cn/blog/meetup_2019_10_26.html',
      },
      {
        title: 'DolphinScheduler json详解',
        author: '进勇',
        editor: '小P',
        dateStr: '2021-05-29',
        desc: 'DolphinScheduler json拆解详细说明',
        link: '/zh-cn/blog/dolphinscheduler_json.html',
      },      
    ],
  },
};
