pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'Apache DolphinScheduler | 首页'
   keywords: 'DolphinScheduler，调度系统'
   description: '页面内容简介'
  # home config
  en-us:
   title: 'Apache DolphinScheduler | Home'
   keywords: 'DolphinScheduler, scheduler, big data'
   description: 'page description'
 community:
  # 社区页配置
  zh-cn:
   title: 'Apache DolphinScheduler | 社区'
   keywords: 'DolphinScheduler, DolphinScheduler新闻，DolphinScheduler动态'
   description: '页面内容简介'
  # community page config
  en-us:
   title: 'Apache DolphinScheduler | Community'
   keywords: 'DolphinScheduler, News，Events'
   description: 'page description'
 blog:
  # 博客列表页配置
  zh-cn:
   title: 'Apache DolphinScheduler | 博客'
   keywords: '博客，DolphinScheduler博客'
   description: '页面内容简介'
  en-us:
   # blog list page config
   title: 'Apache DolphinScheduler | BLOG'
   keywords: 'blog,DolphinScheduler blog'
   description: 'page description'
