# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Change Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'

concurrency:
  group: cd-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mark-fail:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # We do not accept anyone who wants to make some change to directory `docs`, you should
      # consider changing the content in https://github.com/apache/dolphinscheduler-website/tree/history-docs
      # if you want to change the history docs before DolphinScheduler 3.0.0-alpha. Or changing the content
      # in https://github.com/apache/dolphinscheduler/tree/dev/docs for the latest docs.
      - name: mark-failed
        run: |
          exit 1
